# Generated by Django 6.0 on 2025-12-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-upload_time']},
        ),
        migrations.AddField(
            model_name='image',
            name='exposure_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='f_stop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='iso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='file_size',
            field=models.IntegerField(help_text='Unit: KB', null=True),
        ),
    ]
